config/routes.rb
Faqly::Application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'let-me-in' }
  resources :faqs do
    resources :questions, only: [:index] do
        collection do
          get '/:tag', to: 'questions#index', as: :tag
        end
    end
  end

  root to: 'pages#index'

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  belongs_to :user
  has_many :questions



  def tags
    self.questions.pluck('distinct(unnest(tags))')    
  end


  def full_title
    I18n.t 'faq.title', user: user.name, title: name 
  end


end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :faq
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :faqs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter do
    set_x_frame_options
  end



  def set_x_frame_options
    response.headers["X-Frame-Options"] = ''
  end

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController


  before_filter only: [:new, :create] { @faq = Faq.new(faq_params) }


  def new; end

  def create; end





  def faq_params
    if params[:faq]
      params.require(:faq).permit(:title)
    else
      {}
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index;  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @faq = Faq.find_by id: params[:faq_id]
    if params[:tag] && params[:tag].present?
      @questions = Question.where('? = ANY(tags)', params[:tag].to_s).order('created_at ASC')
    end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/faqs/new.html.slim
.row
  .large-12.columns
    = form_for @faq do |f|
      = f.label :title

app/views/faqs/show.html.slim
.row
  .large-12.columns
    header.title
      h1= @faq.full_title 
      span.subheader= @faq.description

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title= content_for?(:title) ? yield(:title) : 'Faqly'

    /! Default styles
    = stylesheet_link_tag :application
    = csrf_meta_tags

  body[id=controller.controller_name class=controller.action_name]
    .head= yield(:header_content)
    .body= yield
    .foot= render 'layouts/footer'
    = javascript_include_tag :application 

app/views/pages/index.html.slim
.login-action
  .row
    .large-12.columns.text-right
      nav
        = link_to "sign up", new_user_registration_path
        = link_to "login", new_user_session_path

.header
  .row.logo-home
    .large-12.columns
      = image_tag "faqto.png", size: '200x200', title: "This is a hover. It's nice."
      h1 It's time to answer those questions 
  .row.main-text-presentation
    .large-12.columns
      p
        | With faq.to you can easily create questions and gather information 
        | about who reads and when. 
  .row.action
    .large-12.large-centered.columns
      = link_to "Get started", new_faq_path, class: :button

.row
  .large-8.large-centered.columns
    hr

.about-content
  .row
    .large-12.columns
      .row.about-info
        .large-4.columns
          = image_tag "file.png"
          h3 Create your awesome FAQ within seconds
          p
            | Insert tags, organize, reorganize and start receiving feedback from 
            | your users!
        .large-4.columns
          = image_tag "profile.png"
          h3 Real answers, real feedback from real users
          p
            | Your users can comment, vote and give feedback about your 
            | questions! FAQs will not be the same.
        .large-4.columns.end
          = image_tag "stats.png"
          h3 Analyse everything everywhere
          p
            | You now can see in real time if your FAQs are being accessed, 
            | stats about visits in your FAQ and comments being written. 
            | Much more to come!

app/views/questions/index.html.slim
= content_for :title, @faq.full_title

= content_for :header_content do
  header.row
    h3.faqly= link_to "faq.to", root_path    
.row
  .large-12.columns
    header.title
      h1= @faq.full_title 
      span.subheader= @faq.description


.row.questions.with_vertical_tags
  
  .large-2.columns
    h4= t 'faq.navigation.head'
    ul.side-nav
      - @faq.tags.each do |tag|
        li[class=(params[:tag] == tag ? 'active' : '')]= link_to tag, tag_faq_questions_path(@faq.user, @faq, tag: tag) 
        li.divider
  .large-10.columns
    - @questions.each do |q|
      h3= q.title
      p=  simple_format(q.answer)

app/views/questions/show.html.slim
h1 Questions#show
p Find me in app/views/questions/show.html.slim